### ISSUE TITLE
Clarification needed on routes affected by middleware.ts file

### ISSUE THREAD

**Issue by rondonjon** [rakkasjs/rakkasjs#112]
According to the documentation, we can add a `middleware.ts` file to the `routes` directory to add custom middleware functions.

Coming from next.js, I was assuming that a `middleware.ts` file would apply to "all" routes on that and the descending levels. According to the documentation however, the middleware will only apply to API routes, which I read as "not to page routes".

Wouldn't it be more intuitive then if the file was named `middleware.api.ts` or similar? And is there a similar way to define a middleware for pages, without having to create / specify a full hattip-entry file?

**Comment by cyco130** [comment]
I understand the confusion, and I think you're right :)

There are two issues to consider here, though.

Suppose you have a setup like this:

```
|- layout.ts
|- foo/
        |- middleware.ts
        |- index.page.ts
```

Wouldn't it be surprising for you that middleware applies to not only `index.page.ts` but also `layout.ts`? That's because layout will be rendered as part of a request to `/foo`.

The second consideration is client routing. Suppose you have a middleware like this:

```ts
export default function middleware(ctx) {
  if (!ctx.session.data.loggedInUser) {
    return new Respons("Unauthorized", { status: 401 });
  }
}
```

If we make the middleware work for pages too, when you visit a page guarded by this middleware, it will work as expected and you'll get a 401. But if you navigate into that page using client-side routing, Rakkas won't even hit the server and it will just render the page because middleware only apply to HTTP requests but page navigation does not necessarily involve an HTTP request.

In the next version of Rakkas, it will be possible to write middleware functions in layouts, and API endpoints in pages. E.g. the layout/middleware and page/API route concepts will be (optionally) merged. But I'm still not sure how I will explain the caveats above to users :)

BTW the correct solution to the problem above is to use [route guards](https://rakkasjs.org/guide/route-guards). They are, in some ways, similar to middleware but they are isomorphic, i.e. they work both on the server and the client so they also work with client-side routing.

**Comment by rondonjon** [comment]
> Wouldn't it be surprising for you that middleware applies to not only index.page.ts but also layout.ts?

True.

> The second consideration is client routing. 

Yes, makes sense.

Thanks for pointing it out, I had not thought of this at all.

> BTW the correct solution to the problem above is to use route guards. They are, in some ways, similar to middleware but they are isomorphic

Again, not sure if I fully understand, but wouldn't this also be handled as one (indeed very particular, admittedly not very "layout"-ish) use case in a layout?

**Comment by cyco130** [comment]
> Based purely on the technical possibilities, couldn't this just as well be solved in a layout

Yes, but route guards are a permanent part of your application, i.e. they're bundled eagerly as part of the router. That's because they can be needed at any time (and synchronously). But layouts are only loaded when they're needed, otherwise the JS bundle would explode in size. In the future, I'll experiment with putting guards in the layout file but extracting the guard code into the router.
