### ISSUE TITLE
Support async server-side init script

### ISSUE THREAD

**Issue by rondonjon** [rakkasjs/rakkasjs#121]
If I understand the docs correctly, the server should be initialized in `entry-hattip.ts`. Is there a way to run `async` initialization code? The default export must be a `HattipHandler`. Options that come to mind:

- also accept a `Promise<HattipHandler>` as default export
- also accept an `async` function as default export that returns `Promise<HattipHandler>`
- extend `HattipHandler` with a hook for async server-side initialization

Thanks

**Comment by cyco130** [comment]
The problem is, server initialization only makes sense in long running servers: Serverless and edge functions don't really have the concept because there's no running server outside of the request/response cycle. Having an initialization hook may give the user the wrong impression that it will only run once even though it will run on (almost) every request on serverless and edge environments.

Having said that, you ca use top-level `await` for async initialization. On environments that don't support top level await, you can use the deferred promise pattern:

```ts
import { createRequestHandler } from "rakkasjs";

const initializationPromise = doSomeAsyncInitialization();

export default createRequestHandler({
  middleware: {
    beforePages: [
      async () => {
        // BeforePages middlewares always run first
        // so we'll ensure that initialization is complete
        // before anything else happens
        await initializationPromise;
      }
    ],
  },
});
```

**Comment by rondonjon** [comment]
Oh my. Of couse. Thanks for bringing that up again. I had totally forgotten that this is all serverless. Need to get rid of these old patterns in my mind.
