### ISSUE TITLE
How to forward request (when in ssr) error status code to ssr status?

### ISSUE THREAD

**Issue by Innei** [rakkasjs/rakkasjs#46]
Hello, this framework is very nice, I really like this framework, in particular, it supports Layout, I've used NextJS before, but he doesn't support Layout. And NextJS not support fetching data on top and inject data by root context.

Rakkas can request data in `Layout.tsx` and then inject it downwards, which is great, or I can use the built-in ErrorBoundary to handle how the request should be rendered in case of errors.

But I've also run into a problem with `useQuery`, that is, requests are not always 2xx, sometimes they may hit a 4xx, such as 404, which throws a `RequestError`, and I can control how it should render the error page by determining the `RequestError` instance, which is great. But it only controls how the error page should be displayed, not the status code of the SSR page, which always returns a 500 status code whenever an exception is thrown.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/41265413/188263492-db5762dc-1c9a-4540-95b3-8c94bed70149.png">

Here I mock a request that is not 2xx and it will throw RequestError.

```tsx
// about.page.tsx
import { useQuery } from "rakkasjs";
import { FC } from "react";

class RequestError extends Error {
  constructor(message: string, public status: number) {
    super(message);
  }
}

const AboutPage: FC = () => {
  const data = useQuery("about", async () => {
    throw new RequestError("404 Not Found", 404); // mock request error, throw RequestError 404
  });
  return (
    <main>
      <h1>About</h1>
      {data.data.text}
    </main>
  );
};

export default AboutPage;

```

```tsx
// layout.tsx
// ..
<ErrorBoundary
        fallbackRender={({ error, resetErrorBoundary }) => (
          <div>
            <h1>An error has occurred</h1>
            <pre>{error.message}</pre>      // catch error
            <button
              onClick={() => {
                resetErrorBoundary();
              }}
            >
              Try again
            </button>
          </div>
        )}
      >
       {children}
      </ErrorBoundary>

//..
```

**Comment by Innei** [comment]
For example, in ErrorRender provide a parameter `res?: ServerResponse`, `res` is optional, but in server side render is always non-null, then I can access NodeJS response and modify the response code via `res?.status = `

**Comment by cyco130** [comment]
Hi! Thank you for your interest!

It is true that throwing from a query function during SSR isn't a good way to handle errors at the present. [Error handling docs](https://rakkasjs.org/guide/error-handling) touches on it:

> [...] it's probably best not to use exceptions for error handling.

It doesn't suggest any alternative but the easiest solution is to handle the error yourself without throwing like [in this example](https://stackblitz.com/edit/github-kukvzj?file=src%2Ftsconfig.json,src%2Froutes%2Findex.page.tsx).

If that's too much of a hustle, [HatTip](https://github.com/hattipjs/hattip) (HTTP server library that Rakkas uses underneath) provides another way to solve this: If your error defines a `toResponse` method that returns a `Response` object, it will be called to build the response. See [this example](https://stackblitz.com/edit/github-kukvzj-jccen1?file=src%2Ftsconfig.json,src%2Froutes%2Findex.page.tsx). Rakkas docs don't provide much detail on HatTip, so you should probably check at least the main readme there to see what else is possible.

Also please note that both methods of setting the status code are "best effort". Since Rakkas does **streaming** SSR, it may be that the headers (and the status code) have already been sent by the time your component is rendered. It happens when your component is buried deep under multiple layers of `Suspense` boundaries. If correct status code is important, you should either disable streaming or set the status code by implementing a [headers function](https://rakkasjs.org/guide/status-and-headers).

Rakkas does [disable streaming for bots](https://rakkasjs.org/guide/dynamic-rendering) automatically, so there should be no SEO problems.

Hope this solves your problems.

**Comment by Innei** [comment]
Thanks. ☺️
