### ISSUE TITLE
Prepass

### ISSUE THREAD

**Issue by sharmapukar217** [rakkasjs/rakkasjs#48]
I need to use prepass to support urql in ssr mode, where can i run prepass from `react-ssr-prepass`

**Comment by cyco130** [comment]
Hi, Rakkas doesn't need `react-ssr-prepass` because it **actually supports Suspense on the server!** :)

First of all, you may not need `urql` at all. Rakkas's builtin `useQuery` is very capable and you can use it for GraphQL [as in this example](https://github.com/rakkasjs/rakkasjs/blob/main/examples/graphql/src/routes/index.page.tsx#L4). You can write your own hook to make it easier to use if you want. It will give you automatic support for document level caching and streaming SSR.

But `urql` provides a few extras such as request deduplication and (optionally) normalized caching. So I've just [added an integration example](https://github.com/rakkasjs/rakkasjs/tree/main/examples/urql), [see it in action here](https://stackblitz.com/github/rakkasjs/rakkasjs/tree/main/examples/urql?file=src%2Froutes%2Findex.page.tsx).

The important bits are in [`entry-hattip.tsx`](https://github.com/rakkasjs/rakkasjs/blob/main/examples/urql/src/entry-hattip.tsx) and [`entry-client.tsx`](https://github.com/rakkasjs/rakkasjs/blob/main/examples/urql/src/entry-client.tsx). It follows `urql`'s SSR docs pretty closely.

One import point which isn't obvious though is [this bit here](https://github.com/rakkasjs/rakkasjs/blob/main/examples/urql/src/routes/layout.tsx#L4). `throttleRenderStream: true` disables streaming so that all data is ready by the time [`emitToDocumentHead`](https://github.com/rakkasjs/rakkasjs/blob/main/examples/urql/src/entry-hattip.tsx#L26) is called. This is still much more efficient than `react-ssr-prepass`.

A better integration would implement a "streaming SSR exchange" for `urql` which would use the `emitBeforeSsrChunk` hook to update the client cache as new data arrives in a similar way that Rakkas's own [`useQuery` does](https://github.com/rakkasjs/rakkasjs/blob/main/packages/rakkasjs/src/features/use-query/server-hooks.tsx#L100) but unfortunately I'm not that familiar with `urql`.

Hope this solves your problem!

**Comment by sharmapukar217** [comment]
thank you so much. I'm liking rakkas js more and more. All I need is here, ssr with remix like actions for form + vite + react ❤️.
