### ISSUE TITLE
usePageGuard hook

### ISSUE THREAD

**Issue by sharmapukar217** [rakkasjs/rakkasjs#49]
instead of using $guard.ts file, if usePageGuard or similar hook can be made available, it would be more efficient :-)

**Comment by cyco130** [comment]
You can implement route guarding by redirecting from a layout or a page, from either the `preload` function or using the `Redirect` component like `if (!loggedIn) return <Redirect url="/login" />`. But it is actually _less efficient_, especially on the client.

Page guards are executed _before_ the page and the layouts are imported so if a page guard rewrites or redirects, the page and the layouts for that route will not be loaded at all.

If you use the `preload` function or the `Redirect` component, Rakkas will load all the layouts and the page, start rendering them, and will only redirect after it encounters the redirection during the render. A hook would have the same problem.

**Comment by sharmapukar217** [comment]
Can't we use concept similar to useSSQ ? I guess SSQ runs on the server before rendering page?

**Comment by cyco130** [comment]
Maybe you can give me an example of what the `usePageGuard` would look like? Where would you put it and how would you use it?

**Comment by sharmapukar217** [comment]
something like using inside useSSQ as it runs on server before rendering page i guess 🤔

**Comment by cyco130** [comment]
But React hooks run _during_ the render. Also it's not enough for them to run on the server if your using `Link`, Rakkas need to be able to run them on the client too.

`useSSQ` doesn't run before the render: When doing server-side rendering, it runs during the render, more or less like normal `useQuery`. When doing client-side rendering, Rakkas sends a request to the server when it encounters a `useSSQ` hook. So if you have something like this:

```ts
function MyComponent(props) {
  const { id } = props;
  useSSQ(() => database.findPokemon(id));
  ...
}
```

Rakkas turns it into something like this for the client build:

```ts
function MyComponent(props) {
  const { id } = props;
  useQuery(() => fetch(`/_data/<BUILD_ID>/<SOME_UNIQUE_ID>/${serialize(id)}`).then(r => deserialize(r));
  ...
}
```

And then a middleware on the server finds the hook body from the unique ID and calls it, then serializes and sends back the result. It can locate the hook body without rendering because it also transforms the server version into something like this:

```ts
function MyComponent(props) {
  const { id } = props;
  useSSQ(() => $runServerSide$[0]([id]));
  ...
}

export const $runServerSide$ = [
  ([id]) => database.findPokemon(id),
];
```

So the hook body is hoisted outside the component so that the run-server-side middleware can access it directly. You can have look at the [client transform](https://github.com/rakkasjs/rakkasjs/blob/main/packages/rakkasjs/src/features/run-server-side/implementation/transform-client-side.test.ts) and [server transform](https://github.com/rakkasjs/rakkasjs/blob/main/packages/rakkasjs/src/features/run-server-side/implementation/transform-server-side.test.ts) to understand what' going on exactly.

So `useSSQ` doesn't run before the render, it runs during the render, like all hooks. We could put the guards in layout and page files (something like `export function guard() { ... }` and do another transform to separate them maybe. But I don't see how a hook can do the same.

If you don't mind waiting for the render, you can always use `return <Redirect ... />` which is not less convenient than a hook.

**Comment by sharmapukar217** [comment]
I would better stick with $guard.ts as i still can extract my code for auth check. It's working for me well.
I was just concerned if hooks are possible to do so.

**Comment by cyco130** [comment]
> I would better stick with $guard.ts as i still can extract my code for auth check. It's working for me well. I was just concerned if hooks are possible to do so.

HatTip just got a [session middleware](https://github.com/hattipjs/hattip/tree/main/packages/middleware/session) (not yet published) so I'll be adding some auth documentation soon.

But I would suggest you to create a backend function, say `getCurrentUser` that extracts the authenticated user (or null) from the request context. Then you can [inject it into the query cache in the server-side `extendPageContext` hook](https://github.com/rakkasjs/rakkas-realworld/blob/1214cf25b83d74e01fcef1c99cc3033f4055834d/src/entry-hattip.ts#L74). This way it will be available to the page guards via [`queryClient.getQueryData`](https://github.com/rakkasjs/rakkas-realworld/blob/1214cf25b83d74e01fcef1c99cc3033f4055834d/src/routes/_private/%24guard.ts#L4) (because guards are synchronous so you can't do anything async to get the auth status). Then you can put the actual query [in your root layout and add a `refetchInterval`](https://github.com/rakkasjs/rakkas-realworld/blob/1214cf25b83d74e01fcef1c99cc3033f4055834d/src/routes/layout.tsx#L9) so that the session doesn't expire. (This example doesn't use `useSSQ` but it would work the same).

Hopefully there will be a `@rakkas/session` package one day to do all this automatically.

**Comment by sharmapukar217** [comment]
Escuse me, I'm wondering if there's a "preview" command like "sveltekit preview" to serve production build with "vite preview". The usecase is to preview with vite's plugin `vite-plugin-mkcert` for https.

**Comment by cyco130** [comment]
Sorry, not yet. But it's a good idea, please open an issue for it so we can remember :)

In the meantime, you can run an HTTPS server by creating a fake certificate pair and using a custom Node server entry. It's not well documented yet but you create a `server.js` file in the root that looks like this:

```js
import { createServer } from "https";
import { createMiddleware } from "rakkasjs/node-adapter";
import handler from "./dist/server/hattip.js";

// For serving static assets. You can also use `express.static` etc. instead if you want).
import sirv from "sirv";

const listener = createMiddleware(handler);
const sirvHandler = sirv("dist/client");

createServer(
  {
    key: fs.readFileSync("mycert.key"),
    cert: fs.readFileSync("mycert.crt"),
  },
  (req, res) =>
    sirvHandler(req, res, () => {
      listener(req, res, () => {
        if (!res.writableEnded) {
          res.statusCode = 404;
          res.end();
        }
      });
    })
).listen(3000, () => {
  console.log("Running on https://localhost:3000");
});
```

and now you can launch your server with `node server.js`.
