### ISSUE TITLE
The status returned from page guard/ useSSM / useSSQ is not setting status

### ISSUE THREAD

**Issue by sharmapukar217** [rakkasjs/rakkasjs#75]
On inspecting the network tab of devtools I always see 200 OK! status even when returning status other than 200 from page guard/ useSSM / useSSQ

**Comment by cyco130** [comment]
Hi!

Page guards can do one of [these four things](https://rakkasjs.org/guide/route-guards):

1. Return `true` to allow the page to be rendered.
2. Return `false` to prevent the page from rendering. In this case the next matching route will be rendered. For example, if you return `false` from the `/foo/bar` route, `/foo/[id]` and `/foo/[...rest]` will be tried, in that order.
3. Return `{ rewrite: string | URL }` to render some other route without redirecting. Useful for redirecting to a login page while keeping the same URL in the address bar for example.
4. Return `{ redirect: string | URL }` to redirect to some other route. This is the only version that accepts `status` and that's only used for the status code of the redirect response.

The idea is that page guards are for determining whether a route is a match or not. They're not supposed to do the response generation, that's pages' job (redirection being an exception).

If you want to return a non-200 response for a page, you can export a [`headers` function](https://rakkasjs.org/guide/status-and-headers). For a group of pages, you can export your `headers` function from a layout (individual pages can still override the layout's result). `headers` function is only called when the page is rendered on the server, it's not called during client-side navigation since headers and status code don't make sense in that case.

Currently there's no way to control the status code and headers returned from a successful `useSSM` or `useSSQ` call. You can throw a `Response` object or an error with a `toResponse` method. And I may add a way to set status and headers but I'm skeptical of its usefulness: `useSS*` is not REST, it's RPC that just happens to use HTTP as a transport layer. And even that could change/become customizable one day. If your app requires semantic HTTP, maybe you should look into API routes.

**Comment by sharmapukar217** [comment]
But on the typedef there's a status field. Isn't this statusCode? 🤔

**Comment by cyco130** [comment]
> But on the typedef there's a status field. Isn't this statusCode? thinking

Only if you return a redirect, so you can chose between 301, 302 etc.The type is:

```ts
boolean | Redirection | { rewrite: string | URL }
```

and only `Redirection` interface has the `status` field.
