### ISSUE TITLE
Code examples in documentation not working

### ISSUE THREAD

**Issue by khalibloo** [rakkasjs/rakkasjs#86]
The code examples in the documentation are failing with a 502 error.

![image](https://user-images.githubusercontent.com/6402969/206855121-a2567aba-783f-4594-981a-cbc8c11f076f.png)

**Comment by cyco130** [comment]
Thanks for reporting, it appears to be a Codesandbox issue, I'll have a closer look tomorrow.

**Comment by cyco130** [comment]
Can't find a solution, I opened an issue: https://github.com/codesandbox/codesandbox-client/issues/7226

I'll migrate to StackBlitz if it doesn't get resolved soon. I already have the code for it. I went with CodeSandbox because it was faster and SB didn't support Firefox at the time. Now it works on Firefox and doesn't seem much slower than CodeSandbox.

**Comment by cyco130** [comment]
Switched to StackBlitz. It doesn't work on Firefox (embeds don't work) but I don't really have a choice until someone takes a look at the issue I opened on CodeSandbox repo.
